language: generic
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: danisbubkis.men
  skip_cleanup: true
  local_dir: ./
  cache_control: "max-age=21600"
